/**
 * reports-templates.ts — Report and consolidated-KOT print templates.
 */

import { EscposBuilder, type ReceiptSection } from './escpos-builder';
import type { TemplateResult } from './receipt-templates';

// ── Helpers ──

function symFor(cur?: string): string { return cur === 'INR' ? '₹' : cur === 'PKR' ? 'Rs' : '$'; }

function today(): string {
  return new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
}

// ═══════════════════════════════════════════════════
//  Generic Report Receipt
// ═══════════════════════════════════════════════════

export interface ReportPrintData {
  title: string;
  subtitle?: string;
  currency?: string;
  /** Column definitions: [header, widthPct] — must sum to 100 */
  columns: [string, number][];
  /** Each row is an array of strings matching column count */
  rows: string[][];
  /** Optional summary rows shown at the bottom (bold) */
  summary?: [string, string][];
  restaurantName?: string;
  totalLabel?: string;
}

export function buildReportReceipt(
  data: ReportPrintData,
  paperWidth: number,
): TemplateResult {
  const sym = symFor(data.currency);
  const b = new EscposBuilder(paperWidth);
  const sc: ReceiptSection[] = [];
  const w = b.width;

  b.init();

  // Header
  b.alignCenter();
  b.doubleOn();
  b.boldLine(data.restaurantName || 'Nexora Solution');
  b.doubleOff();

  sc.push({ type: 'headline', text: data.restaurantName || 'Nexora Solution' });

  // Report title
  b.feed();
  b.thickLine();
  b.boldCentered(data.title.toUpperCase());
  if (data.subtitle) b.centered(data.subtitle);
  b.centered(`Printed: ${today()}`);
  b.thickLine();
  b.feed();

  sc.push({ type: 'blank' });
  sc.push({ type: 'thick-separator' });
  sc.push({ type: 'bold-centered', text: data.title.toUpperCase() });
  if (data.subtitle) sc.push({ type: 'centered', text: data.subtitle });
  sc.push({ type: 'centered', text: `Printed: ${today()}` });
  sc.push({ type: 'thick-separator' });
  sc.push({ type: 'blank' });

  // Column headers
  b.boldOn();
  b.tableRow(data.columns.map(([h, pct]) => [h, pct] as [string, number]));
  b.boldOff();
  b.dashedLine();

  const headerLine = data.columns.map(([h, pct]) => {
    const colW = Math.floor(w * pct / 100);
    return h.length > colW ? h.slice(0, colW - 1) + ' ' : h.padEnd(colW, ' ');
  }).join('').trimEnd();
  sc.push({ type: 'table-row', text: headerLine });
  sc.push({ type: 'separator' });

  // Data rows
  for (const row of data.rows) {
    const cols: [string, number][] = row.map((cell, i) => [cell, data.columns[i]?.[1] ?? 10]);
    b.tableRow(cols);
    const rowLine = cols.map(([cell, pct]) => {
      const colW = Math.floor(w * pct / 100);
      return cell.length > colW ? cell.slice(0, colW - 1) + ' ' : cell.padEnd(colW, ' ');
    }).join('').trimEnd();
    sc.push({ type: 'table-row', text: rowLine });
  }

  b.dashedLine();
  sc.push({ type: 'separator' });

  // Summary
  if (data.summary && data.summary.length > 0) {
    b.feed();
    for (const [label, value] of data.summary) {
      b.boldRow(label, value);
      sc.push({ type: 'bold-row', left: label, right: value });
    }
    b.thickLine();
    sc.push({ type: 'thick-separator' });
  }

  // Footer
  b.feed();
  b.centered(`Total rows: ${data.rows.length}`);
  b.centered('Generated by Nexora Solution POS');
  sc.push({ type: 'blank' });
  sc.push({ type: 'subtitle', text: `Total rows: ${data.rows.length}` });
  sc.push({ type: 'subtitle', text: 'Generated by Nexora Solution POS' });

  b.cut();
  return { builder: b, sections: sc };
}

// ═══════════════════════════════════════════════════
//  Consolidated Kitchen KOT (Print All)
// ═══════════════════════════════════════════════════

export interface KitchenOrderData {
  orderNumber: string;
  orderType: string;
  table: string;
  orderStatus: string;
  elapsed: string;
  cartRows: Array<{ itemName: string; qty: number; note?: string }>;
}

export function buildConsolidatedKOT(
  orders: KitchenOrderData[],
  paperWidth: number,
): TemplateResult {
  const b = new EscposBuilder(paperWidth);
  const sc: ReceiptSection[] = [];
  const w = b.width;

  b.init();
  b.alignCenter();
  b.doubleOn();
  b.boldLine('KITCHEN BOARD');
  b.doubleOff();
  b.centered(`Consolidated View — ${today()}`);
  b.centered(`${orders.length} active order${orders.length !== 1 ? 's' : ''}`);
  b.dashedLine();

  sc.push({ type: 'headline', text: 'KITCHEN BOARD' });
  sc.push({ type: 'centered', text: `Consolidated View — ${today()}` });
  sc.push({ type: 'centered', text: `${orders.length} active order${orders.length !== 1 ? 's' : ''}` });
  sc.push({ type: 'separator' });

  for (const order of orders) {
    b.feed();
    b.boldOn().doubleWidthOn();
    b.line(`#${order.orderNumber}`);
    b.doubleWidthOff().boldOff();
    b.row('Type:', order.orderType);
    b.row('Table:', order.table || '—');
    b.row('Status:', order.orderStatus);
    b.row('Waiting:', order.elapsed);
    b.dashedLine();

    sc.push({ type: 'blank' });
    sc.push({ type: 'bold-row', left: `#${order.orderNumber}`, right: order.orderStatus });
    sc.push({ type: 'row', left: 'Type:', right: order.orderType });
    sc.push({ type: 'row', left: 'Table:', right: order.table || '—' });
    sc.push({ type: 'row', left: 'Waiting:', right: order.elapsed });
    sc.push({ type: 'separator' });

    for (const item of order.cartRows) {
      b.line(`  • ${item.itemName} x${item.qty}`);
      if (item.note) b.line(`    [${item.note}]`);
      sc.push({ type: 'item', text: `${item.itemName} x${item.qty}`, subtext: item.note || undefined });
    }
    b.dashedLine();
    sc.push({ type: 'separator' });
  }

  b.feed();
  b.thickLine();
  b.centered('END OF KITCHEN BOARD');
  b.thickLine();
  sc.push({ type: 'blank' });
  sc.push({ type: 'thick-separator' });
  sc.push({ type: 'centered', text: 'END OF KITCHEN BOARD' });
  sc.push({ type: 'thick-separator' });

  // Calculate column widths for a clean table row
  const cols: [string, number][] = [['Order #', 25], ['Type', 20], ['Table', 20], ['Status', 15], ['Items', 20]];
  const headerLine = cols.map(([h]) => h).join('  ');
  // Don't bother with table precision — the above section is the main content

  b.cut();
  return { builder: b, sections: sc };
}
