import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: ['./src/renderer/**/*.{ts,tsx}', './index.html'],
  theme: {
    extend: {
      colors: {
        surface: {
          DEFAULT: 'rgb(var(--color-surface) / <alpha-value>)',
          secondary: 'rgb(var(--color-surface-secondary) / <alpha-value>)',
          tertiary: 'rgb(var(--color-surface-tertiary) / <alpha-value>)',
          elevated: 'rgb(var(--color-surface-elevated) / <alpha-value>)',
        },
        content: {
          DEFAULT: 'rgb(var(--color-content) / <alpha-value>)',
          secondary: 'rgb(var(--color-content-secondary) / <alpha-value>)',
          tertiary: 'rgb(var(--color-content-tertiary) / <alpha-value>)',
          inverse: 'rgb(var(--color-content-inverse) / <alpha-value>)',
        },
        border: {
          DEFAULT: 'rgb(var(--color-border) / <alpha-value>)',
          strong: 'rgb(var(--color-border-strong) / <alpha-value>)',
        },
        primary: {
          DEFAULT: 'rgb(var(--color-primary) / <alpha-value>)',
          hover: 'rgb(var(--color-primary-hover) / <alpha-value>)',
          light: 'rgb(var(--color-primary-light) / <alpha-value>)',
          content: 'rgb(var(--color-primary-content) / <alpha-value>)',
        },
        accent: {
          DEFAULT: 'rgb(var(--color-accent) / <alpha-value>)',
          hover: 'rgb(var(--color-accent-hover) / <alpha-value>)',
        },
        iconbar: {
          DEFAULT: 'rgb(var(--color-iconbar) / <alpha-value>)',
          hover: 'rgb(var(--color-iconbar-hover) / <alpha-value>)',
          active: 'rgb(var(--color-iconbar-active) / <alpha-value>)',
          text: 'rgb(var(--color-iconbar-text) / <alpha-value>)',
          'text-active': 'rgb(var(--color-iconbar-text-active) / <alpha-value>)',
        },
        sidebar: {
          DEFAULT: 'rgb(var(--color-sidebar) / <alpha-value>)',
          hover: 'rgb(var(--color-sidebar-hover) / <alpha-value>)',
          active: 'rgb(var(--color-sidebar-active) / <alpha-value>)',
          text: 'rgb(var(--color-sidebar-text) / <alpha-value>)',
          'text-active': 'rgb(var(--color-sidebar-text-active) / <alpha-value>)',
        },
        pos: {
          ground: 'rgb(var(--pos-ground) / <alpha-value>)',
          bar: 'rgb(var(--pos-bar) / <alpha-value>)',
          card: 'rgb(var(--pos-card) / <alpha-value>)',
          'card-border': 'rgb(var(--pos-card-border) / <alpha-value>)',
          divider: 'rgb(var(--pos-divider) / <alpha-value>)',
          grid: 'rgb(var(--pos-grid) / <alpha-value>)',
          axis: 'rgb(var(--pos-axis) / <alpha-value>)',
          ink: 'rgb(var(--pos-ink) / <alpha-value>)',
          muted: 'rgb(var(--pos-muted) / <alpha-value>)',
          primary: 'rgb(var(--pos-primary) / <alpha-value>)',
          'primary-dark': 'rgb(var(--pos-primary-dark) / <alpha-value>)',
          'primary-soft': 'rgb(var(--pos-primary-soft) / <alpha-value>)',
          deep: 'rgb(var(--pos-deep) / <alpha-value>)',
          rail: 'rgb(var(--pos-rail) / <alpha-value>)',
          'deep-tile': 'rgb(var(--pos-deep-tile) / <alpha-value>)',
          'deep-border': 'rgb(var(--pos-deep-border) / <alpha-value>)',
          'on-deep': 'rgb(var(--pos-on-deep-muted) / <alpha-value>)',
          'rail-icon': 'rgb(var(--pos-rail-icon) / <alpha-value>)',
          lime: 'rgb(var(--pos-lime) / <alpha-value>)',
          'lime-border': 'rgb(var(--pos-lime-border) / <alpha-value>)',
          mid: 'rgb(var(--pos-mid) / <alpha-value>)',
          pale: 'rgb(var(--pos-pale) / <alpha-value>)',
          'paid-bg': 'rgb(var(--pos-paid-bg) / <alpha-value>)',
          'paid-fg': 'rgb(var(--pos-paid-fg) / <alpha-value>)',
          'prep-bg': 'rgb(var(--pos-prep-bg) / <alpha-value>)',
          'prep-fg': 'rgb(var(--pos-prep-fg) / <alpha-value>)',
          'pending-bg': 'rgb(var(--pos-pending-bg) / <alpha-value>)',
          'pending-fg': 'rgb(var(--pos-pending-fg) / <alpha-value>)',
          'cancel-bg': 'rgb(var(--pos-cancel-bg) / <alpha-value>)',
          'cancel-fg': 'rgb(var(--pos-cancel-fg) / <alpha-value>)',
        },
        success: 'rgb(var(--color-success) / <alpha-value>)',
        warning: 'rgb(var(--color-warning) / <alpha-value>)',
        danger: 'rgb(var(--color-danger) / <alpha-value>)',
        info: 'rgb(var(--color-info) / <alpha-value>)',
      },
      spacing: {
        rail: '72px',
        topbar: '68px',
        iconbar: 'var(--iconbar-width)',
        sidebar: 'var(--sidebar-width)',
        'sidebar-collapsed': 'var(--sidebar-collapsed-width)',
        header: 'var(--header-height)',
        'bottom-bar': 'var(--bottom-bar-height)',
        'right-panel': 'var(--right-panel-width)',
      },
      fontFamily: {
        sans: ['Instrument Sans', 'Inter', 'Segoe UI', 'system-ui', '-apple-system', 'sans-serif'],
        display: ['Bricolage Grotesque Variable', 'Instrument Sans', 'Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'Consolas', 'monospace'],
      },
      borderRadius: {
        card: 'var(--pos-radius-card)',
        tile: 'var(--pos-radius-tile)',
        btn: 'var(--pos-radius-btn)',
        DEFAULT: '0.375rem',
        sm: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
      },
      boxShadow: {
        panel: '0 1px 3px rgba(0,0,0,0.08), 0 1px 2px rgba(0,0,0,0.06)',
        dropdown: '0 4px 16px rgba(0,0,0,0.12), 0 2px 4px rgba(0,0,0,0.08)',
        card: '0 1px 2px rgba(0,0,0,0.04)',
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/typography')],
};

export default config;
